### ISSUE TITLE
Exception while acquiring new image from swapchain

### ISSUE THREAD

**Issue by Brtosz** [janhsimon/xrvk#3]
The exception occurs  while acquiring new image from swapchain,  it doesn't occur on oculus quest 2, but when I tested it on HTC VIVE PRO it occured
![obraz](https://user-images.githubusercontent.com/113719273/227925491-7c641519-c70b-4141-85cb-5c8007110e18.png)

**Comment by damian-tomczak** [comment]
We have also tested it in two independent environments.
It also occurs on Win10.

**Comment by janhsimon** [comment]
I'm surprised to see `XR_APILAYER_NOVENDOR` show up in your stacktrace in the bottom right. I am not sure what exactly that means - but it may or may not be a hint.

Two quick questions for troubleshooting:
1. Do you see any kind of debug output in the console at all when the crash occurs? The program writes both Vulkan and OpenXR debug output from the respective validation layers.
2. Just to be sure: Have you remembered to change the OpenXR runtime from Oculus to SteamVR when switching from your Quest 2 to the Vive Pro? To do so, you need to open SteamVR and go to the menu button in the top left, Settings -> Advanced Settings: Show -> Developer -> Set SteamVR as OpenXR Runtime.

Hope this helps!

**Comment by damian-tomczak** [comment]
Okay, turned out that the error occurs only in the case when we are using HTC Vive Pro and on the system OpenXR-Toolkit is installed. @janhsimon Thank for your message <3
